{"uuid":"84d83d4e-ce63-49aa-a37b-51bbde62c5e2","historyId":"e56fccb5310b1555ebfa1430a03472bf","fullName":"LoginTests.UnSuccessfullLogin","labels":[{"name":"package","value":"LoginTests"},{"name":"testClass","value":"LoginTests"},{"name":"testMethod","value":"UnSuccessfullLogin"},{"name":"parentSuite","value":"Default Suite"},{"name":"suite","value":"AmazonTestAutomation"},{"name":"subSuite","value":"LoginTests"},{"name":"host","value":"DESKTOP-B3EE8VA"},{"name":"thread","value":"17104@DESKTOP-B3EE8VA.main(1)"},{"name":"framework","value":"testng"},{"name":"language","value":"java"}],"links":[],"name":"Başarısız kullanıcı giriş kontrolü","status":"failed","statusDetails":{"known":false,"muted":false,"flaky":false,"message":"expected [\nBir sorun oluştu] but found [Bir sorun oluştu]","trace":"java.lang.AssertionError: expected [\nBir sorun oluştu] but found [Bir sorun oluştu]\r\n\tat org.testng.Assert.fail(Assert.java:111)\r\n\tat org.testng.Assert.failNotEquals(Assert.java:1578)\r\n\tat org.testng.Assert.assertEqualsImpl(Assert.java:150)\r\n\tat org.testng.Assert.assertEquals(Assert.java:132)\r\n\tat org.testng.Assert.assertEquals(Assert.java:656)\r\n\tat org.testng.Assert.assertEquals(Assert.java:666)\r\n\tat Base.BaseLibrary.assertEqualsText(BaseLibrary.java:21)\r\n\tat LoginTests.UnSuccessfullLogin(LoginTests.java:28)\r\n\tat java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)\r\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:580)\r\n\tat org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)\r\n\tat org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)\r\n\tat org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)\r\n\tat org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)\r\n\tat org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)\r\n\tat org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)\r\n\tat org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)\r\n\tat org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)\r\n\tat java.base/java.util.ArrayList.forEach(ArrayList.java:1597)\r\n\tat org.testng.TestRunner.privateRun(TestRunner.java:739)\r\n\tat org.testng.TestRunner.run(TestRunner.java:614)\r\n\tat org.testng.SuiteRunner.runTest(SuiteRunner.java:421)\r\n\tat org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)\r\n\tat org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)\r\n\tat org.testng.SuiteRunner.run(SuiteRunner.java:312)\r\n\tat org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)\r\n\tat org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)\r\n\tat org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)\r\n\tat org.testng.TestNG.runSuitesLocally(TestNG.java:1208)\r\n\tat org.testng.TestNG.runSuites(TestNG.java:1112)\r\n\tat org.testng.TestNG.run(TestNG.java:1079)\r\n\tat com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:65)\r\n\tat com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)\r\n"},"stage":"finished","steps":[],"attachments":[{"name":"Bir sorun oluştu hata mesajı ekrandan çekilir","source":"f4dcb84f-8457-4bae-8530-f18c97958d56-attachment.txt","type":"text/plain"}],"parameters":[],"start":1734080722887,"stop":1734080727066}